# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SubpackageBundleDownLoadTypeFB(object):
    Manual = 0
    Auto = 1


class ChunkCompressMethodFB(object):
    None_ = 0
    Lzma = 1
    Zip = 2


class AssetMapBundleFB(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AssetMapBundleFB()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAssetMapBundleFB(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AssetMapBundleFB
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AssetMapBundleFB
    def H2b(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = AssetHashMapBundleFB()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AssetMapBundleFB
    def H2bLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # AssetMapBundleFB
    def H2bIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # AssetMapBundleFB
    def P2b(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = AssetPathMapBundleFB()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AssetMapBundleFB
    def P2bLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # AssetMapBundleFB
    def P2bIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def AssetMapBundleFBStart(builder):
    builder.StartObject(2)

def AssetMapBundleFBAddH2b(builder, h2b):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(h2b), 0)

def AssetMapBundleFBStartH2bVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def AssetMapBundleFBAddP2b(builder, p2b):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(p2b), 0)

def AssetMapBundleFBStartP2bVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def AssetMapBundleFBEnd(builder):
    return builder.EndObject()



class AssetHashMapBundleFB(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AssetHashMapBundleFB()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAssetHashMapBundleFB(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AssetHashMapBundleFB
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AssetHashMapBundleFB
    def Hash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AssetHashMapBundleFB
    def Bundle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def AssetHashMapBundleFBStart(builder):
    builder.StartObject(2)

def AssetHashMapBundleFBAddHash(builder, hash):
    builder.PrependUint32Slot(0, hash, 0)

def AssetHashMapBundleFBAddBundle(builder, bundle):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(bundle), 0)

def AssetHashMapBundleFBEnd(builder):
    return builder.EndObject()



class AssetPathMapBundleFB(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AssetPathMapBundleFB()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAssetPathMapBundleFB(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AssetPathMapBundleFB
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AssetPathMapBundleFB
    def Path(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AssetPathMapBundleFB
    def Bundle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def AssetPathMapBundleFBStart(builder):
    builder.StartObject(2)

def AssetPathMapBundleFBAddPath(builder, path):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(path), 0)

def AssetPathMapBundleFBAddBundle(builder, bundle):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(bundle), 0)

def AssetPathMapBundleFBEnd(builder):
    return builder.EndObject()



class Bundle2AtlasListFB(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Bundle2AtlasListFB()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBundle2AtlasListFB(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Bundle2AtlasListFB
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Bundle2AtlasListFB
    def B2a(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Bundle2AtlasFB()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Bundle2AtlasListFB
    def B2aLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Bundle2AtlasListFB
    def B2aIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Bundle2AtlasListFBStart(builder):
    builder.StartObject(1)

def Bundle2AtlasListFBAddB2a(builder, b2a):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(b2a), 0)

def Bundle2AtlasListFBStartB2aVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def Bundle2AtlasListFBEnd(builder):
    return builder.EndObject()



class Bundle2AtlasFB(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Bundle2AtlasFB()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBundle2AtlasFB(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Bundle2AtlasFB
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Bundle2AtlasFB
    def Bundle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Bundle2AtlasFB
    def Atlas(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # Bundle2AtlasFB
    def AtlasLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Bundle2AtlasFB
    def AtlasIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def Bundle2AtlasFBStart(builder):
    builder.StartObject(2)

def Bundle2AtlasFBAddBundle(builder, bundle):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(bundle), 0)

def Bundle2AtlasFBAddAtlas(builder, atlas):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(atlas), 0)

def Bundle2AtlasFBStartAtlasVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def Bundle2AtlasFBEnd(builder):
    return builder.EndObject()



class CheckSumInfosFB(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CheckSumInfosFB()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCheckSumInfosFB(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CheckSumInfosFB
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CheckSumInfosFB
    def Infos(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = CheckSumInfoFB()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CheckSumInfosFB
    def InfosLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CheckSumInfosFB
    def InfosIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def CheckSumInfosFBStart(builder):
    builder.StartObject(1)

def CheckSumInfosFBAddInfos(builder, infos):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(infos), 0)

def CheckSumInfosFBStartInfosVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def CheckSumInfosFBEnd(builder):
    return builder.EndObject()



class CheckSumInfoFB(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CheckSumInfoFB()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCheckSumInfoFB(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CheckSumInfoFB
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CheckSumInfoFB
    def RelativePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CheckSumInfoFB
    def CRc32(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CheckSumInfoFB
    def Md5(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CheckSumInfoFB
    def IsBundle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def CheckSumInfoFBStart(builder):
    builder.StartObject(4)

def CheckSumInfoFBAddRelativePath(builder, relativePath):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(relativePath), 0)

def CheckSumInfoFBAddCRc32(builder, cRc32):
    builder.PrependInt32Slot(1, cRc32, 0)

def CheckSumInfoFBAddMd5(builder, md5):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(md5), 0)

def CheckSumInfoFBAddIsBundle(builder, isBundle):
    builder.PrependBoolSlot(3, isBundle, 0)

def CheckSumInfoFBEnd(builder):
    return builder.EndObject()



class SubpackageFileInChunkInfoFB(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SubpackageFileInChunkInfoFB()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSubpackageFileInChunkInfoFB(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SubpackageFileInChunkInfoFB
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SubpackageFileInChunkInfoFB
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SubpackageFileInChunkInfoFB
    def Crc32(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SubpackageFileInChunkInfoFB
    def ChunkName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SubpackageFileInChunkInfoFB
    def Size(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SubpackageFileInChunkInfoFB
    def OffsetChunk(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SubpackageFileInChunkInfoFB
    def Md5(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SubpackageFileInChunkInfoFB
    def BundleDownLoadType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # SubpackageFileInChunkInfoFB
    def Necessary(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # SubpackageFileInChunkInfoFB
    def IsBundle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def SubpackageFileInChunkInfoFBStart(builder):
    builder.StartObject(9)

def SubpackageFileInChunkInfoFBAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def SubpackageFileInChunkInfoFBAddCrc32(builder, crc32):
    builder.PrependInt32Slot(1, crc32, 0)

def SubpackageFileInChunkInfoFBAddChunkName(builder, chunkName):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(chunkName), 0)

def SubpackageFileInChunkInfoFBAddSize(builder, size):
    builder.PrependUint32Slot(3, size, 0)

def SubpackageFileInChunkInfoFBAddOffsetChunk(builder, offsetChunk):
    builder.PrependUint32Slot(4, offsetChunk, 0)

def SubpackageFileInChunkInfoFBAddMd5(builder, md5):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(md5), 0)

def SubpackageFileInChunkInfoFBAddBundleDownLoadType(builder, bundleDownLoadType):
    builder.PrependInt8Slot(6, bundleDownLoadType, 0)

def SubpackageFileInChunkInfoFBAddNecessary(builder, necessary):
    builder.PrependBoolSlot(7, necessary, 0)

def SubpackageFileInChunkInfoFBAddIsBundle(builder, isBundle):
    builder.PrependBoolSlot(8, isBundle, 0)

def SubpackageFileInChunkInfoFBEnd(builder):
    return builder.EndObject()



class SubpackageChunkInfoFB(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SubpackageChunkInfoFB()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSubpackageChunkInfoFB(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SubpackageChunkInfoFB
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SubpackageChunkInfoFB
    def Tag(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SubpackageChunkInfoFB
    def FileName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SubpackageChunkInfoFB
    def Crc32(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SubpackageChunkInfoFB
    def Md5(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SubpackageChunkInfoFB
    def FileSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SubpackageChunkInfoFB
    def CompressMethod(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # SubpackageChunkInfoFB
    def ChunkFiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = SubpackageFileInChunkInfoFB()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SubpackageChunkInfoFB
    def ChunkFilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SubpackageChunkInfoFB
    def ChunkFilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def SubpackageChunkInfoFBStart(builder):
    builder.StartObject(7)

def SubpackageChunkInfoFBAddTag(builder, tag):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(tag), 0)

def SubpackageChunkInfoFBAddFileName(builder, fileName):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(fileName), 0)

def SubpackageChunkInfoFBAddCrc32(builder, crc32):
    builder.PrependInt32Slot(2, crc32, 0)

def SubpackageChunkInfoFBAddMd5(builder, md5):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(md5), 0)

def SubpackageChunkInfoFBAddFileSize(builder, fileSize):
    builder.PrependUint32Slot(4, fileSize, 0)

def SubpackageChunkInfoFBAddCompressMethod(builder, compressMethod):
    builder.PrependInt8Slot(5, compressMethod, 0)

def SubpackageChunkInfoFBAddChunkFiles(builder, chunkFiles):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(chunkFiles), 0)

def SubpackageChunkInfoFBStartChunkFilesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def SubpackageChunkInfoFBEnd(builder):
    return builder.EndObject()



class SubpackageTagDepedentFB(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SubpackageTagDepedentFB()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSubpackageTagDepedentFB(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SubpackageTagDepedentFB
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SubpackageTagDepedentFB
    def Tag(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SubpackageTagDepedentFB
    def DependentTags(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # SubpackageTagDepedentFB
    def DependentTagsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SubpackageTagDepedentFB
    def DependentTagsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def SubpackageTagDepedentFBStart(builder):
    builder.StartObject(2)

def SubpackageTagDepedentFBAddTag(builder, tag):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(tag), 0)

def SubpackageTagDepedentFBAddDependentTags(builder, dependentTags):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(dependentTags), 0)

def SubpackageTagDepedentFBStartDependentTagsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def SubpackageTagDepedentFBEnd(builder):
    return builder.EndObject()



class SubpackageInfoFB(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SubpackageInfoFB()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSubpackageInfoFB(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SubpackageInfoFB
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SubpackageInfoFB
    def Chunks(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = SubpackageChunkInfoFB()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SubpackageInfoFB
    def ChunksLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SubpackageInfoFB
    def ChunksIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # SubpackageInfoFB
    def TagDependent(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = SubpackageTagDepedentFB()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SubpackageInfoFB
    def TagDependentLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SubpackageInfoFB
    def TagDependentIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def SubpackageInfoFBStart(builder):
    builder.StartObject(2)

def SubpackageInfoFBAddChunks(builder, chunks):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(chunks), 0)

def SubpackageInfoFBStartChunksVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def SubpackageInfoFBAddTagDependent(builder, tagDependent):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(tagDependent), 0)

def SubpackageInfoFBStartTagDependentVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def SubpackageInfoFBEnd(builder):
    return builder.EndObject()



class UnloadbleAssetBundle(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UnloadbleAssetBundle()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUnloadbleAssetBundle(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UnloadbleAssetBundle
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UnloadbleAssetBundle
    def Bundles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # UnloadbleAssetBundle
    def BundlesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UnloadbleAssetBundle
    def BundlesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def UnloadbleAssetBundleStart(builder):
    builder.StartObject(1)

def UnloadbleAssetBundleAddBundles(builder, bundles):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(bundles), 0)

def UnloadbleAssetBundleStartBundlesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def UnloadbleAssetBundleEnd(builder):
    return builder.EndObject()



