namespace Trickcal.Shared;

public enum AugmentCondition : int {
    None = 0,
    Purchase = 1,
    Release = 2,
    AugmentActive = 3,
    AugmentActiveAfter = 4,
    ParentAugmentAttackHit = 5,
    NormalAttackHit = 6,
    BasicAttackHit = 7,
    PowerAttackHit = 8,
    DirectAttackHit = 9,
    SkillAttackHit = 10,
    SpSkillAttackHit = 11,
    UltimateSkillAttackHit = 12,
    CriticalAttackHit = 13,
    KillEnemy = 14,
    SkillUseBefore = 15,
    SpSkillUseBefore = 16,
    UltimateSkillUseBefore = 17,
    SkillUseAfter = 18,
    SpSkillUseAfter = 19,
    UltimateSkillUseAfter = 20,
    NormalAttackDamaged = 21,
    DirectAttackDamaged = 22,
    GainHeal = 23,
    KillEnemyWithSkill = 24,
    TimeInterval = 25,
    OnHitSkillEffect = 26,
    BattleTime = 27,
    CriticalAttackHitIncludeAugment = 28,
    OnBeforeSkillEffect = 29,
    CriticalAttackDamaged = 30,
    BattleStart = 31,
    HpPercentLow = 32,
    HpPercentLowOnce = 33,
    PurchaseOtherAugment = 34,
    TeamBuild = 35,
    NormalAttackBefore = 36,
    BasicAttackBefore = 37,
    PowerAttackBefore = 38,
    NormalAttackAfter = 39,
    BasicAttackAfter = 40,
    PowerAttackAfter = 41,
    RequiredAugmentCount = 42
}
