namespace Trickcal.Shared;

public enum InteractionContentsType : int {
    StoryMenu = 0,
    Housing = 1,
    Home = 2,
    Shop = 3,
    ThemeEventShop = 4,
    ThemeEventQuest = 5,
    CashShop = 6,
    MiniEvent = 7,
    GuildShop = 8,
    BingoEvent = 9,
    HousingLayout = 10,
    SoloEndQuest = 11,
    Fake = 12,
    Maid = 13,
    LobbyHighlight = 14,
    MemoryPiece = 15,
    Arcade = 16,
    SoloEndAppear = 17,
    ThemeEventLottery = 18,
    AugmentChallenge = 19,
    ThemeEventAuthority = 20,
    ProductionSkin = 21,
    HeroGrowEvent = 22,
    ThemeEventLobby = 23,
    HomeEvent = 24,
    ThemeEventBattle = 25,
    ThemeEventTile = 26,
    ThemeEventPointEvent = 27,
    GachaponEvent = 28,
    ThemeEventDailyLottery = 29,
    CookingTycoon = 30,
    AreaChallenge = 31,
    Constellation = 32,
    MiniGame = 33,
    ThemeEventSideStory = 34,
    ArcadeSeasonShop = 35,
    ArcadeSeasonQuest = 36,
    ThemeEventDeduction = 37,
    TitleHighlight = 38,
    CardMileageShop = 39,
    EventLottery = 40
}
