namespace Trickcal.Shared;

public enum ModeType : short {
    None = 0,
    Quest = 1,
    SkillEnhance = 2,
    LevelUp = 3,
    Gold = 4,
    Board = 5,
    Upgrade = 6,
    Tower = 7,
    SoloRaid = 8,
    DualArena = 9,
    DualArenaDefense = 10,
    TrickcalRank = 11,
    TrickcalRankDefense = 12,
    ThemeEvent = 13,
    EquipPart = 14,
    SoloEnd = 15,
    Rerun = 16,
    Aside = 17,
    GlobalBattleEventNormal = 18,
    GlobalBattleEventBoss = 19,
    SelectBattleEventNormal = 20,
    SelectBattleEventAside = 21,
    SelectBattleEventGold = 22,
    AugmentChallenge = 23,
    StoryBattle = 24,
    SelectBattleEventAuthority = 25,
    SelectBattleEventLevelUp = 26,
    Tutorial = 27,
    SelectBattleEventMaxParty = 28,
    Tower_Global = 29,
    SelectBattleEventUserSkill = 30,
    UserSkillChallenge = 31,
    ChaosArena = 32,
    ChaosArenaDefense = 33,
    WWE = 34,
    UserSkillAsideChallenge = 35,
    AreaChallenge = 36,
    ArcadeSeason = 37,
    TrainingRoomSoloRaid = 38,
    TrainingRoomSoloEnd = 39,
    TrainingRoomQuest = 40,
    Test = 99
}
