namespace Trickcal.Shared;

public enum OperationDataType : short {
    None = 0,
    CashShop = 1,
    AttendanceDaily = 2,
    Pass = 3,
    HeroGachaPickup = 4,
    SpectacleCard = 5,
    Event = 6,
    ThemeEvent = 7,
    DayLimitQuest = 8,
    MiniEvent = 9,
    DropEvent = 10,
    BingoEvent = 11,
    LobbyEvent = 12,
    MixedEvent = 13,
    AccountReturnEvent = 14,
    UserLvPass = 15,
    AnniversaryPage = 16,
    DailyTimeEvent = 17,
    HeroMotionExperience = 18,
    PreviewEvent = 19,
    CardGachaPickup = 20,
    TitleHeroSetting = 21,
    DiscountEvent = 22,
    HeroGrowEvent = 23,
    GachaponEvent = 24,
    PuppetEvent = 25,
    WebLink = 26,
    BoostEvent = 27,
    StoryLockOverRide = 28,
    PvpSchedule = 51,
    SoloEndSchedule = 52,
    SoloRaidSchedule = 53,
    PetDispatch = 54,
    RecallSchedule = 55,
    ChaosArenaSchedule = 56,
    CookingTycoonSchedule = 57,
    WWESchedule = 58,
    ArcadeSeason = 59,
    TowerBattle = 60,
    ChainGift = 61,
    ContentsMaintenance = 100
}
