namespace Trickcal.Shared;

public enum TokenEventType : int {
    None = 0,
    AppOpen = 1,
    CI = 2,
    CDNStart = 3,
    CDNSuccess = 4,
    GameStart = 5,
    TermsOfUse = 6,
    Login_Apple = 7,
    Login_Google = 8,
    Login_Guest = 9,
    strech = 10,
    CreateNickname = 11,
    StageEnd = 12,
    RaidStageEnd = 13,
    PVPEnd = 14,
    Tutorial = 15,
    UserLevel = 16,
    FirstPurchase = 17,
    Gacha = 18,
    GachaEnd = 19,
    ShopPurchase = 20,
    BeginnerQuest = 21,
    DailyQuestClear = 22,
    QuestClear = 23,
    ShowAds = 24,
    UseCoupon = 25,
    FirstTalk = 26,
    ThemeEnter = 27,
    StageStart = 28,
    StageWave2 = 29
}
